platform:
  - x64

configuration:
  - Debug
#  - Release

image:
  - Visual Studio 2019

skip_commits:
  files:
    - README.md
    - LICENSE
    - CODE_OF_CONDUCT.md
    - CHANGELOG.md
    - .gitignore
    - .github/*

environment:
  PYTHON: C:\Python39-x64
  PYTHON_SCRIPTS: C:\Python39-x64\Scripts
  matrix:
    - TOOLSET: v142
#    - TOOLSET: ClangCL

clone_folder: c:/playlunky/

install:
  - SET PATH=%PYTHON%;%PYTHON_SCRIPTS%;%PATH%
  - git submodule update --init --recursive
  - python --version
  - python -m pip --version
  - python -m pip install conan --upgrade
  - python -m pip install numpy
  - conan user
  - conan --version

before_build:
  - ps: >-
      $ENV:PATH="$ENV:PYTHON;$ENV:PYTHON_SCRIPTS;$ENV:PATH"

      mkdir build

      cd build
  - cmd: cmake c:/playlunky/ -G"Visual Studio 16 2019" -A x64 -T %TOOLSET% -DPLAYLUNKY_CONAN_VERBOSE=ON

build_script:
  - SET PATH=%PYTHON%;%PYTHON_SCRIPTS%;%PATH%
  - cmake --build . --config %CONFIGURATION%
#
#test_script:
#- ctest -C %CONFIGURATION% --output-on-failure
